spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_SECURITY_SERVICE_OAUTH:http://localhost:9000/oauth2/jwks}
  main:
    web-application-type: reactive
server:
  port: ${SERVER_PORT:8082}
microservices:
  microservice1-url: ${MICROSERVICE1_URL:http://localhost:8080}
  microservice2-url: ${MICROSERVICE1_URL:http://localhost:8083}
springdoc:
  api-docs:
    enable: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Maker Service
        url: /v3/api-docs/api/maker
      - name: Microservice 2
        url: /v3/api-docs/micro
    disable-swagger-default-url: true
    operation-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
management:
  health:
    circuitbreakers:
      enable: true
  endpoints:
    web:
      exposure:
        include: health, metrics, circuitbreakers, info
  endpoint:
    health:
      show-detail: always
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5 #numero de llamadas que monitorea antes de cambiar de estado
        minimum-number-of-calls: 3 #minimo de llamadas para evaluar el estado
        failure-rate-threshold: 50 #si el 50% de las ultimas 5 llamadas fallan, el circuito se abre
        wait-duration-in-open-state: 10s #tiempo de espera antes de probar si el servicio volvio
        permitted-number-of-calls-in-half-open-state: 2 #intentos en HALF_open antes de cerrar
  timelimiter:
    instances:
      makerServiceCircuitBreaker:
        timeout-duration: 5s #Cualquier request que tarde mas de 2s se considera fallo
gateway:
  retry:
    attempts: 3