spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_SECURITY_SERVICE_OAUTH:http://localhost:9000/oauth2/jwks}
  main:
    web-application-type: reactive
server:
  port: ${SERVER_PORT:8082}
microservices:
  microservice1-url: ${MICROSERVICE1_URL:http://localhost:8080}
  microservice2-url: ${MICROSERVICE1_URL:http://localhost:8083}