spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
server:
  port: ${SERVER_PORT:8082}
microservices:
  microservice1-url: ${MICROSERVICE1_URL:http://localhost:8080}
  microservice2-url: ${MICROSERVICE1_URL:http://localhost:8083}