spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${URL_SECURITY_SERVICE_OAUTH:http://localhost:9000/oauth2/jwks}
  main:
    web-application-type: reactive
server:
  port: ${SERVER_PORT:8082}
microservices:
  microservice1-url: ${MICROSERVICE1_URL:http://localhost:8080}
  microservice2-url: ${MICROSERVICE1_URL:http://localhost:8083}
springdoc:
  api-docs:
    enable: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Maker Service
        url: /v3/api-docs/api/maker
      - name: Microservice 2
        url: /v3/api-docs/micro
    disable-swagger-default-url: true
    operation-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
